### PR TITLE
Fix access to wysiwyg editor settings

### PR DESCRIPTION
**Pull request by gotcha**
In Plone 5 wysiwyg editor settings have moved from portal_properties to registry.

This is the PR for master/Plone 6 (together with 5.2)

Antoine Duchêne contributor agreement is being prepared.

### CODE REVIEW

**Comment by gotcha** [comment]
@mauritsvanrees Is there a reason why you merged #44 and not this one ?

**Review by mauritsvanrees — APPROVED** [review]
> @mauritsvanrees Is there a reason why you merged #44 and not this one ?

I did not see this one yet. I don't usually interact with this repo.

Also, some tests are failing. Some jobs pass, so they might be unrelated random failures, but not sure.

I approve this PR, provided the tests are green.

**Comment by gotcha** [comment]
@jenkins-plone-org please run jobs

**Comment by gotcha** [comment]
@mauritsvanrees Tests are green.

I also pushed the test fix to branch `1.2.x`.

**Comment by mauritsvanrees** [comment]
I have released this as 1.3.6.

**Comment by gotcha** [comment]
@mauritsvanrees Great. Thanks

**Pull request merged**
